USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS RETAIL_DB;

CREATE SCHEMA IF NOT EXISTS RETAIL_DB.BRONZE;
CREATE SCHEMA IF NOT EXISTS RETAIL_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS RETAIL_DB.MODEL;
CREATE SCHEMA IF NOT EXISTS RETAIL_DB.GOLD;
CREATE SCHEMA IF NOT EXISTS RETAIL_DB.ML;
