CREATE TABLE IF NOT EXISTS RETAIL_DB.GOLD.KPI_MONTHLY_REVENUE (
    YEAR_MONTH STRING,
    REVENUE NUMBER(18,2),
    ORDERS NUMBER,
    UNIQUE_CUSTOMERS NUMBER
);

CREATE TABLE IF NOT EXISTS RETAIL_DB.GOLD.KPI_DAILY_REVENUE (
    ORDER_DATE DATE,
    REVENUE NUMBER(18,2),
    ORDERS NUMBER
);

CREATE TABLE IF NOT EXISTS RETAIL_DB.GOLD.KPI_CUSTOMER_RFM (
    CUSTOMER_ID STRING,
    RECENCY_DAYS NUMBER,
    FREQUENCY NUMBER,
    MONETARY NUMBER(18,2),
    LAST_ORDER_DATE DATE
);
