USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE RETAIL_DB;

CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS MODEL;
CREATE SCHEMA IF NOT EXISTS GOLD;

CREATE OR REPLACE FILE FORMAT BRONZE.FF_CSV
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE STAGE BRONZE.RAW_STAGE
  FILE_FORMAT = BRONZE.FF_CSV;
