USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE RETAIL_DB;

CREATE OR REPLACE VIEW GOLD.V_KPI_MONTHLY_REVENUE AS
SELECT
  d.YEAR_MONTH,
  SUM(i.REVENUE) AS REVENUE,
  COUNT(DISTINCT o.ORDER_ID) AS ORDERS,
  COUNT(DISTINCT o.CUSTOMER_KEY) AS UNIQUE_CUSTOMERS
FROM MODEL.FACT_ORDERS o
JOIN MODEL.FACT_ORDER_ITEMS i ON i.ORDER_ID = o.ORDER_ID
JOIN MODEL.DIM_DATE d ON d.DATE_KEY = o.ORDER_DATE
WHERE o.ORDER_STATUS = 'delivered'
GROUP BY 1
ORDER BY 1;

CREATE OR REPLACE VIEW GOLD.V_KPI_DAILY_REVENUE AS
SELECT
  o.ORDER_DATE,
  SUM(i.REVENUE) AS REVENUE,
  COUNT(DISTINCT o.ORDER_ID) AS ORDERS
FROM MODEL.FACT_ORDERS o
JOIN MODEL.FACT_ORDER_ITEMS i ON i.ORDER_ID = o.ORDER_ID
WHERE o.ORDER_STATUS = 'delivered'
GROUP BY 1
ORDER BY 1;

CREATE OR REPLACE VIEW GOLD.V_KPI_CUSTOMER_RFM AS
WITH last_dt AS (
  SELECT MAX(ORDER_DATE) AS MAXD
  FROM MODEL.FACT_ORDERS
  WHERE ORDER_STATUS = 'delivered'
),
base AS (
  SELECT
    CUSTOMER_KEY AS CUSTOMER_ID,
    MAX(ORDER_DATE) AS LAST_ORDER_DATE,
    COUNT(DISTINCT ORDER_ID) AS FREQUENCY
  FROM MODEL.FACT_ORDERS
  WHERE ORDER_STATUS = 'delivered'
  GROUP BY 1
),
mon AS (
  SELECT
    o.CUSTOMER_KEY AS CUSTOMER_ID,
    SUM(i.REVENUE) AS MONETARY
  FROM MODEL.FACT_ORDERS o
  JOIN MODEL.FACT_ORDER_ITEMS i ON i.ORDER_ID = o.ORDER_ID
  WHERE o.ORDER_STATUS = 'delivered'
  GROUP BY 1
)
SELECT
  b.CUSTOMER_ID,
  DATEDIFF('day', b.LAST_ORDER_DATE, (SELECT MAXD FROM last_dt)) AS RECENCY_DAYS,
  b.FREQUENCY,
  m.MONETARY,
  b.LAST_ORDER_DATE
FROM base b
JOIN mon m USING (CUSTOMER_ID);
