USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE RETAIL_DB;

ALTER TABLE SILVER.CUSTOMERS ADD COLUMN IF NOT EXISTS CUSTOMER_UNIQUE_ID STRING;
ALTER TABLE SILVER.CUSTOMERS ADD COLUMN IF NOT EXISTS CUSTOMER_ZIP_CODE_PREFIX STRING;

MERGE INTO SILVER.ORDERS t
USING (
  SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    TRY_TO_TIMESTAMP_NTZ(ORDER_PURCHASE_TIMESTAMP)      AS ORDER_PURCHASE_TS,
    TRY_TO_TIMESTAMP_NTZ(ORDER_APPROVED_AT)             AS ORDER_APPROVED_TS,
    TRY_TO_TIMESTAMP_NTZ(ORDER_DELIVERED_CARRIER_DATE)  AS ORDER_DELIVERED_CARRIER_TS,
    TRY_TO_TIMESTAMP_NTZ(ORDER_DELIVERED_CUSTOMER_DATE) AS ORDER_DELIVERED_CUSTOMER_TS,
    TRY_TO_TIMESTAMP_NTZ(ORDER_ESTIMATED_DELIVERY_DATE) AS ORDER_ESTIMATED_DELIVERY_TS
  FROM BRONZE.ORDERS_RAW
) s
ON t.ORDER_ID = s.ORDER_ID
WHEN MATCHED THEN UPDATE SET
  CUSTOMER_ID = s.CUSTOMER_ID,
  ORDER_STATUS = s.ORDER_STATUS,
  ORDER_PURCHASE_TS = s.ORDER_PURCHASE_TS,
  ORDER_APPROVED_TS = s.ORDER_APPROVED_TS,
  ORDER_DELIVERED_CARRIER_TS = s.ORDER_DELIVERED_CARRIER_TS,
  ORDER_DELIVERED_CUSTOMER_TS = s.ORDER_DELIVERED_CUSTOMER_TS,
  ORDER_ESTIMATED_DELIVERY_TS = s.ORDER_ESTIMATED_DELIVERY_TS,
  UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  ORDER_ID, CUSTOMER_ID, ORDER_STATUS,
  ORDER_PURCHASE_TS, ORDER_APPROVED_TS,
  ORDER_DELIVERED_CARRIER_TS, ORDER_DELIVERED_CUSTOMER_TS,
  ORDER_ESTIMATED_DELIVERY_TS
) VALUES (
  s.ORDER_ID, s.CUSTOMER_ID, s.ORDER_STATUS,
  s.ORDER_PURCHASE_TS, s.ORDER_APPROVED_TS,
  s.ORDER_DELIVERED_CARRIER_TS, s.ORDER_DELIVERED_CUSTOMER_TS,
  s.ORDER_ESTIMATED_DELIVERY_TS
);

MERGE INTO SILVER.ORDER_ITEMS t
USING (
  SELECT
    ORDER_ID,
    ORDER_ITEM_ID,
    PRODUCT_ID,
    SELLER_ID,
    TRY_TO_TIMESTAMP_NTZ(SHIPPING_LIMIT_DATE) AS SHIPPING_LIMIT_TS,
    PRICE,
    FREIGHT_VALUE,
    (PRICE + FREIGHT_VALUE) AS REVENUE
  FROM BRONZE.ORDER_ITEMS_RAW
) s
ON t.ORDER_ID = s.ORDER_ID AND t.ORDER_ITEM_ID = s.ORDER_ITEM_ID
WHEN MATCHED THEN UPDATE SET
  PRODUCT_ID = s.PRODUCT_ID,
  SELLER_ID = s.SELLER_ID,
  SHIPPING_LIMIT_TS = s.SHIPPING_LIMIT_TS,
  PRICE = s.PRICE,
  FREIGHT_VALUE = s.FREIGHT_VALUE,
  REVENUE = s.REVENUE,
  UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  ORDER_ID, ORDER_ITEM_ID, PRODUCT_ID, SELLER_ID, SHIPPING_LIMIT_TS,
  PRICE, FREIGHT_VALUE, REVENUE
) VALUES (
  s.ORDER_ID, s.ORDER_ITEM_ID, s.PRODUCT_ID, s.SELLER_ID, s.SHIPPING_LIMIT_TS,
  s.PRICE, s.FREIGHT_VALUE, s.REVENUE
);

MERGE INTO SILVER.CUSTOMERS t
USING (
  SELECT
    CUSTOMER_ID,
    CUSTOMER_UNIQUE_ID,
    CUSTOMER_ZIP_CODE_PREFIX,
    CUSTOMER_CITY,
    CUSTOMER_STATE
  FROM BRONZE.CUSTOMERS_RAW
) s
ON t.CUSTOMER_ID = s.CUSTOMER_ID
WHEN MATCHED THEN UPDATE SET
  CUSTOMER_UNIQUE_ID = s.CUSTOMER_UNIQUE_ID,
  CUSTOMER_ZIP_CODE_PREFIX = s.CUSTOMER_ZIP_CODE_PREFIX,
  CUSTOMER_CITY = s.CUSTOMER_CITY,
  CUSTOMER_STATE = s.CUSTOMER_STATE
WHEN NOT MATCHED THEN INSERT (
  CUSTOMER_ID, CUSTOMER_UNIQUE_ID, CUSTOMER_ZIP_CODE_PREFIX, CUSTOMER_CITY, CUSTOMER_STATE
) VALUES (
  s.CUSTOMER_ID, s.CUSTOMER_UNIQUE_ID, s.CUSTOMER_ZIP_CODE_PREFIX, s.CUSTOMER_CITY, s.CUSTOMER_STATE
);

CREATE OR REPLACE TABLE MODEL.DIM_CUSTOMER AS
SELECT DISTINCT
  TO_VARCHAR(CUSTOMER_UNIQUE_ID) AS CUSTOMER_KEY,
  CUSTOMER_ID,
  CUSTOMER_UNIQUE_ID,
  CUSTOMER_CITY,
  CUSTOMER_STATE,
  CURRENT_TIMESTAMP() AS UPDATED_AT
FROM SILVER.CUSTOMERS
WHERE CUSTOMER_UNIQUE_ID IS NOT NULL;

CREATE OR REPLACE TABLE MODEL.DIM_DATE AS
SELECT DISTINCT
  TO_DATE(ORDER_PURCHASE_TS) AS DATE_KEY,
  TO_CHAR(TO_DATE(ORDER_PURCHASE_TS), 'YYYY-MM') AS YEAR_MONTH,
  EXTRACT(YEAR FROM TO_DATE(ORDER_PURCHASE_TS)) AS YEAR,
  EXTRACT(MONTH FROM TO_DATE(ORDER_PURCHASE_TS)) AS MONTH,
  EXTRACT(DAY FROM TO_DATE(ORDER_PURCHASE_TS)) AS DAY
FROM SILVER.ORDERS
WHERE ORDER_PURCHASE_TS IS NOT NULL;

CREATE OR REPLACE TABLE MODEL.FACT_ORDERS AS
SELECT
  o.ORDER_ID,
  TO_VARCHAR(c.CUSTOMER_UNIQUE_ID) AS CUSTOMER_KEY,
  o.ORDER_STATUS,
  TO_DATE(o.ORDER_PURCHASE_TS) AS ORDER_DATE,
  CURRENT_TIMESTAMP() AS UPDATED_AT
FROM SILVER.ORDERS o
JOIN SILVER.CUSTOMERS c ON c.CUSTOMER_ID = o.CUSTOMER_ID
WHERE o.ORDER_PURCHASE_TS IS NOT NULL;

CREATE OR REPLACE TABLE MODEL.FACT_ORDER_ITEMS AS
SELECT
  ORDER_ID,
  ORDER_ITEM_ID,
  PRODUCT_ID,
  REVENUE,
  CURRENT_TIMESTAMP() AS UPDATED_AT
FROM SILVER.ORDER_ITEMS;
