USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE RETAIL_DB;
USE SCHEMA GOLD;

SELECT 'KPI_MONTHLY_REVENUE rowcount > 0' AS check_name,
       IFF(COUNT(*) > 0, 'PASS', 'FAIL') AS status,
       COUNT(*) AS metric
FROM KPI_MONTHLY_REVENUE
UNION ALL
SELECT 'KPI_DAILY_REVENUE rowcount > 0',
       IFF(COUNT(*) > 0, 'PASS', 'FAIL'),
       COUNT(*)
FROM KPI_DAILY_REVENUE
UNION ALL
SELECT 'KPI_CUSTOMER_RFM rowcount > 0',
       IFF(COUNT(*) > 0, 'PASS', 'FAIL'),
       COUNT(*)
FROM KPI_CUSTOMER_RFM;

SELECT 'MONTHLY: YEAR_MONTH is NOT NULL' AS check_name,
       IFF(SUM(IFF(YEAR_MONTH IS NULL, 1, 0)) = 0, 'PASS', 'FAIL') AS status,
       SUM(IFF(YEAR_MONTH IS NULL, 1, 0)) AS null_rows
FROM KPI_MONTHLY_REVENUE
UNION ALL
SELECT 'DAILY: ORDER_DATE is NOT NULL',
       IFF(SUM(IFF(ORDER_DATE IS NULL, 1, 0)) = 0, 'PASS', 'FAIL'),
       SUM(IFF(ORDER_DATE IS NULL, 1, 0))
FROM KPI_DAILY_REVENUE
UNION ALL
SELECT 'RFM: CUSTOMER_ID is NOT NULL',
       IFF(SUM(IFF(CUSTOMER_ID IS NULL, 1, 0)) = 0, 'PASS', 'FAIL'),
       SUM(IFF(CUSTOMER_ID IS NULL, 1, 0))
FROM KPI_CUSTOMER_RFM;
