USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE RETAIL_DB;

CREATE TABLE IF NOT EXISTS BRONZE.ORDERS_RAW (
  ORDER_ID STRING,
  CUSTOMER_ID STRING,
  ORDER_STATUS STRING,
  ORDER_PURCHASE_TIMESTAMP STRING,
  ORDER_APPROVED_AT STRING,
  ORDER_DELIVERED_CARRIER_DATE STRING,
  ORDER_DELIVERED_CUSTOMER_DATE STRING,
  ORDER_ESTIMATED_DELIVERY_DATE STRING,
  INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS BRONZE.ORDER_ITEMS_RAW (
  ORDER_ID STRING,
  ORDER_ITEM_ID NUMBER,
  PRODUCT_ID STRING,
  SELLER_ID STRING,
  SHIPPING_LIMIT_DATE STRING,
  PRICE NUMBER(18,2),
  FREIGHT_VALUE NUMBER(18,2),
  INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS BRONZE.CUSTOMERS_RAW (
  CUSTOMER_ID STRING,
  CUSTOMER_UNIQUE_ID STRING,
  CUSTOMER_ZIP_CODE_PREFIX STRING,
  CUSTOMER_CITY STRING,
  CUSTOMER_STATE STRING,
  INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS SILVER.ORDERS (
  ORDER_ID STRING,
  CUSTOMER_ID STRING,
  ORDER_STATUS STRING,
  ORDER_PURCHASE_TS TIMESTAMP_NTZ,
  ORDER_APPROVED_TS TIMESTAMP_NTZ,
  ORDER_DELIVERED_CARRIER_TS TIMESTAMP_NTZ,
  ORDER_DELIVERED_CUSTOMER_TS TIMESTAMP_NTZ,
  ORDER_ESTIMATED_DELIVERY_TS TIMESTAMP_NTZ,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS SILVER.ORDER_ITEMS (
  ORDER_ID STRING,
  ORDER_ITEM_ID NUMBER,
  PRODUCT_ID STRING,
  SELLER_ID STRING,
  SHIPPING_LIMIT_TS TIMESTAMP_NTZ,
  PRICE NUMBER(18,2),
  FREIGHT_VALUE NUMBER(18,2),
  REVENUE NUMBER(18,2),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS SILVER.CUSTOMERS (
  CUSTOMER_ID STRING,
  CUSTOMER_UNIQUE_ID STRING,
  CUSTOMER_ZIP_CODE_PREFIX STRING,
  CUSTOMER_CITY STRING,
  CUSTOMER_STATE STRING,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS MODEL.DIM_CUSTOMER (
  CUSTOMER_KEY STRING,
  CUSTOMER_ID STRING,
  CUSTOMER_UNIQUE_ID STRING,
  CUSTOMER_CITY STRING,
  CUSTOMER_STATE STRING,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS MODEL.DIM_DATE (
  DATE_KEY DATE,
  YEAR_MONTH STRING,
  YEAR NUMBER,
  MONTH NUMBER,
  DAY NUMBER
);

CREATE TABLE IF NOT EXISTS MODEL.FACT_ORDERS (
  ORDER_ID STRING,
  CUSTOMER_KEY STRING,
  ORDER_STATUS STRING,
  ORDER_DATE DATE,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS MODEL.FACT_ORDER_ITEMS (
  ORDER_ID STRING,
  ORDER_ITEM_ID NUMBER,
  PRODUCT_ID STRING,
  REVENUE NUMBER(18,2),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
