USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE RETAIL_DB;

SELECT 'BRONZE.ORDERS_RAW' AS OBJ, COUNT(*) AS ROW_COUNT FROM BRONZE.ORDERS_RAW
UNION ALL SELECT 'BRONZE.ORDER_ITEMS_RAW', COUNT(*) FROM BRONZE.ORDER_ITEMS_RAW
UNION ALL SELECT 'BRONZE.CUSTOMERS_RAW', COUNT(*) FROM BRONZE.CUSTOMERS_RAW
UNION ALL SELECT 'SILVER.ORDERS', COUNT(*) FROM SILVER.ORDERS
UNION ALL SELECT 'SILVER.ORDER_ITEMS', COUNT(*) FROM SILVER.ORDER_ITEMS
UNION ALL SELECT 'SILVER.CUSTOMERS', COUNT(*) FROM SILVER.CUSTOMERS
UNION ALL SELECT 'MODEL.DIM_CUSTOMER', COUNT(*) FROM MODEL.DIM_CUSTOMER
UNION ALL SELECT 'MODEL.DIM_DATE', COUNT(*) FROM MODEL.DIM_DATE
UNION ALL SELECT 'MODEL.FACT_ORDERS', COUNT(*) FROM MODEL.FACT_ORDERS
UNION ALL SELECT 'MODEL.FACT_ORDER_ITEMS', COUNT(*) FROM MODEL.FACT_ORDER_ITEMS
ORDER BY OBJ;

SELECT 'MODEL.FACT_ORDER_ITEMS duplicate (ORDER_ID, ORDER_ITEM_ID)' AS CHECK_NAME,
       IFF(COUNT(*)=0,'PASS','FAIL') AS STATUS,
       COUNT(*) AS DUP_KEYS
FROM (
  SELECT ORDER_ID, ORDER_ITEM_ID
  FROM MODEL.FACT_ORDER_ITEMS
  GROUP BY 1,2
  HAVING COUNT(*) > 1
);

SELECT 'FACT_ORDERS missing DIM_CUSTOMER' AS CHECK_NAME,
       IFF(COUNT(*)=0,'PASS','FAIL') AS STATUS,
       COUNT(*) AS BAD_ROWS
FROM MODEL.FACT_ORDERS f
LEFT JOIN MODEL.DIM_CUSTOMER d
  ON d.CUSTOMER_KEY = f.CUSTOMER_KEY
WHERE d.CUSTOMER_KEY IS NULL;

SELECT 'FACT_ORDERS missing DIM_DATE' AS CHECK_NAME,
       IFF(COUNT(*)=0,'PASS','FAIL') AS STATUS,
       COUNT(*) AS BAD_ROWS
FROM MODEL.FACT_ORDERS f
LEFT JOIN MODEL.DIM_DATE d
  ON d.DATE_KEY = f.ORDER_DATE
WHERE d.DATE_KEY IS NULL;
